clear
echo "\e[1;31m \n"
uname -a
echo " while ( love & passion ) { \n \e[1;33m    for( fight = 0 ; rights < freedom ; rights++ ) \n       fight = standup( rights ); \e[1;32m \n     free( babylon ); \n } \n \n"

### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
